### ISSUE TITLE
Login page stays stuck when passing wrong email or password

### ISSUE THREAD

**Issue by odv** [jscraft-org/mentoring-project-4#40]
@serge-nikitin I'm using bcrypt.compare as written in the documentation to test whether the password from the login form matches the one in the database. When entering the correct email and password, I'm successfully redirected to the profile page but if I serve incorrect data, the login page stays stuck in loading more.

Here is what I have so far: https://github.com/jscraft-org/mentoring-project-4/blob/feature-authentication/src/router.js#L12

I'm not sure how to debug this.

**Comment by serge-nikitin** [comment]
Have I told you about special repos for questions? As I remember, I've told about it.

When you have any question, you should create a brand new repo with minimum set of libraries (1 library is the best) with minimum number of files (1 first is the best). Where you can describe your problem:
- I'm passing such data...
- I'm expecting to get such data...
- But I'm receiving such result. 

Why?

Otherwise it looks like you don't do nothing and just don't try to solve the problem.

**Comment by odv** [comment]
@serge-nikitin  Yes, you have told me but I was too focused on this issue and forgot about this debugging method. 
I went and did what you said above and now understand what I was doing wrong.
